
name: publish
on:
  push:
    branches: [ release ]
  release:
    types: [ published ]

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.5.22307.18
    - name: Pack
      run: ./build.sh --pack
    - name: Publish package
      run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json artifacts/pack/*.nupkg